#Use root/example as user/password credentials
version: "3.1"

services:
    myUniSocialDb:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: myUniSocialDb
            MYSQL_ROOT_PASSWORD: 968dce130fc3
        volumes:
            - "myUniSocial-mysql-data:/var/lib/mysql"

    backend:
        build: ./
        restart: always
        ports:
            - 127.0.0.1:9030:3001
        volumes:
            - "app-data:/app/public/images/"

    adminer:
        image: adminer
        restart: always
        ports:
            - 9031:8080

volumes:
    myUniSocial-mysql-data:
    app-data:
