# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: myCircleDatabase
      MYSQL_ROOT_PASSWORD: Flat90210112
    volumes:
      - "mysql-data:/var/lib/mysql"

  backend:
    build: ./

    ports:
      - 9010:3001
    volumes:
      - "app-data:/app/public/images/"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9011:8080

volumes:
  mysql-data:
  app-data:
